name: ci
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          version: v0.10.0
